//
//  AutoGenerationActionAction.m
//
//  Generated by MD2 framework on Fri Jul 05 12:05:30 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

#import "SpecificAppData.h"
#import "Md2Library/EventBindingAction.h"
#import "Md2Library/EventTrigger.h"
#import "Md2Library/RegisterMappingAction.h"
#import "Md2Library/UnregisterMappingAction.h"
#import "Md2Library/ValidatorBindingAction.h"
#import "Md2Library/ViewEvent.h"
#import "AutoGenerationActionAction.h"
#import "Md2Library/NotEmptyValidator.h"
#import "Md2Library/IntegerValidator.h"
#import "Md2Library/NumberRangeValidator.h"

@implementation AutoGenerationActionAction

+(void) performAction: (Event *) event
{
	[self performCustomAction];
}

+(void) performCustomAction
{
	[RegisterMappingAction performAction: [RegisterMappingEvent eventWithDataMapper: [SpecificAppData groupTabController].dataMapper contentProvider: [SpecificAppData groupContentProviderContentProvider] dataKey: @"name" identifier: @"nameTextInput"]];
	[RegisterMappingAction performAction: [RegisterMappingEvent eventWithDataMapper: [SpecificAppData detailTabController].dataMapper contentProvider: [SpecificAppData contactContentProviderContentProvider] dataKey: @"photo" identifier: @"photoTextInput"]];
	[RegisterMappingAction performAction: [RegisterMappingEvent eventWithDataMapper: [SpecificAppData detailTabController].dataMapper contentProvider: [SpecificAppData contactContentProviderContentProvider] dataKey: @"name" identifier: @"nameTextInput1"]];
	[RegisterMappingAction performAction: [RegisterMappingEvent eventWithDataMapper: [SpecificAppData detailTabController].dataMapper contentProvider: [SpecificAppData contactContentProviderContentProvider] dataKey: @"firstname" identifier: @"firstnameTextInput"]];
	[RegisterMappingAction performAction: [RegisterMappingEvent eventWithDataMapper: [SpecificAppData detailTabController].dataMapper contentProvider: [SpecificAppData contactContentProviderContentProvider] dataKey: @"phone" identifier: @"phoneTextInput"]];
	[RegisterMappingAction performAction: [RegisterMappingEvent eventWithDataMapper: [SpecificAppData detailTabController].dataMapper contentProvider: [SpecificAppData contactContentProviderContentProvider] dataKey: @"email" identifier: @"emailTextInput"]];
	[RegisterMappingAction performAction: [RegisterMappingEvent eventWithDataMapper: [SpecificAppData detailTabController].dataMapper contentProvider: [SpecificAppData contactContentProviderContentProvider] dataKey: @"street" identifier: @"streetTextInput"]];
	[RegisterMappingAction performAction: [RegisterMappingEvent eventWithDataMapper: [SpecificAppData detailTabController].dataMapper contentProvider: [SpecificAppData contactContentProviderContentProvider] dataKey: @"city" identifier: @"cityTextInput"]];
	[RegisterMappingAction performAction: [RegisterMappingEvent eventWithDataMapper: [SpecificAppData detailTabController].dataMapper contentProvider: [SpecificAppData contactContentProviderContentProvider] dataKey: @"zipCode" identifier: @"zipCodeTextInput"]];
	[ValidatorBindingAction performAction: [ValidatorBindingEvent eventWithController: [SpecificAppData detailTabController] validator: [[NotEmptyValidator alloc] init] identifier: @"firstnameTextInput"]];
	[ValidatorBindingAction performAction: [ValidatorBindingEvent eventWithController: [SpecificAppData detailTabController] validator: [[IntegerValidator alloc] init] identifier: @"photoTextInput"]];
	[ValidatorBindingAction performAction: [ValidatorBindingEvent eventWithController: [SpecificAppData detailTabController] validator: [[IntegerValidator alloc] init] identifier: @"phoneTextInput"]];
	[ValidatorBindingAction performAction: [ValidatorBindingEvent eventWithController: [SpecificAppData groupTabController] validator: [[NotEmptyValidator alloc] init] identifier: @"nameTextInput"]];
	[ValidatorBindingAction performAction: [ValidatorBindingEvent eventWithController: [SpecificAppData detailTabController] validator: [[IntegerValidator alloc] init] identifier: @"zipCodeTextInput"]];
	[ValidatorBindingAction performAction: [ValidatorBindingEvent eventWithController: [SpecificAppData detailTabController] validator: [[NumberRangeValidator alloc] initWithMinimum: 1000.0 maximum: 99999.0] identifier: @"zipCodeTextInput"]];
	[ValidatorBindingAction performAction: [ValidatorBindingEvent eventWithController: [SpecificAppData detailTabController] validator: [[NotEmptyValidator alloc] init] identifier: @"nameTextInput1"]];
}

@end