//
//  ContactsTabView.m
//
//  Generated by MD2 framework on Fri Jul 05 12:05:29 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

#import "ContactsTabView.h"
#import "Md2Library/FlowLayout.h"

@implementation ContactsTabView

-(id) init
{
	self = [super init];
	if (self)
		identifier = @"contactsTab";
	return self;
}

-(void) loadView
{
	[super loadView];
	
	defaultLayout = [[FlowLayout alloc] initWithFrame: LayoutFrame(self.frame) numberElements: 1 direction: Vertical identifier: @"contactsTabDefaultLayout"];
	
	[self addWidget: [self createButtonWidget: @"editContactButton"]];
	
	[contentView addSubview: defaultLayout];
}

@end