//
//  ContactEntity.h
//
//  Generated by MD2 framework on Fri Jul 05 12:05:28 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

#import <CoreData/CoreData.h>
#import "Md2Library/DataTransferObject.h"

@interface ContactEntity : DataTransferObject

@property (retain, nonatomic) NSNumber* photo;
@property (retain, nonatomic) NSString* name;
@property (retain, nonatomic) NSString* firstname;
@property (retain, nonatomic) NSNumber* phone;
@property (retain, nonatomic) NSString* email;
@property (retain, nonatomic) NSString* street;
@property (retain, nonatomic) NSString* city;
@property (retain, nonatomic) NSNumber* zipCode;

@end

