//
//  ContactEntity.m
//
//  Generated by MD2 framework on Fri Jul 05 12:05:28 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

#import "ContactEntity.h"

@implementation ContactEntity

@dynamic photo;
@dynamic name;
@dynamic firstname;
@dynamic phone;
@dynamic email;
@dynamic street;
@dynamic city;
@dynamic zipCode;

@end
