//
//  ContactsTabController.m
//
//  Generated by MD2 framework on Fri Jul 05 12:05:29 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

#import "ContactsTabController.h"
#import "ContactsTabView.h"

@interface ContactsTabController ()
@end

@implementation ContactsTabController

-(id) init
{
	self = [super init];
	if (self)
	{
		contentView = [[ContactsTabView alloc] init];
		[self loadView];
	}
	return self;
}

@end