//
//  DefaultStyle.h
//  TariffCalculator
//
//  Generated by MD2 framework on Fri Jul 05 12:05:30 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

#define DefaultFont [UIFont systemFontOfSize: 17.0]

#define DefaultTextColor [UIColor blackColor]
