//
//  DetailTabController.m
//
//  Generated by MD2 framework on Fri Jul 05 12:05:29 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

#import "DetailTabController.h"
#import "DetailTabView.h"

@interface DetailTabController ()
@end

@implementation DetailTabController

-(id) init
{
	self = [super init];
	if (self)
	{
		contentView = [[DetailTabView alloc] init];
		[self loadView];
	}
	return self;
}

@end