//
//  GroupTabView.m
//
//  Generated by MD2 framework on Fri Jul 05 12:05:29 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

#import "GroupTabView.h"
#import "Md2Library/FlowLayout.h"

@implementation GroupTabView

-(id) init
{
	self = [super init];
	if (self)
		identifier = @"groupTab";
	return self;
}

-(void) loadView
{
	[super loadView];
	
	defaultLayout = [[FlowLayout alloc] initWithFrame: LayoutFrame(self.frame) numberElements: 2 direction: Vertical identifier: @"groupTabDefaultLayout"];
	
	[self addWidget: [self createTextFieldWidget: @"nameTextInput" hasInfoButton: NO]];
	
	FlowLayout *persistenceLayout = [[FlowLayout alloc] initWithFrame: LayoutFrame(self.frame) numberElements: 1 direction: Horizontal identifier: @"persistenceLayout"];
	[self addWidget: [self createButtonWidget: @"saveButton"] toLayout: persistenceLayout];
	[self addView: persistenceLayout identifier: @"persistenceLayout"];
	
	
	[contentView addSubview: defaultLayout];
}

@end