//
//  GroupTabController.m
//
//  Generated by MD2 framework on Fri Jul 05 12:05:29 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

#import "GroupTabController.h"
#import "GroupTabView.h"

@interface GroupTabController ()
@end

@implementation GroupTabController

-(id) init
{
	self = [super init];
	if (self)
	{
		contentView = [[GroupTabView alloc] init];
		[self loadView];
	}
	return self;
}

@end