//
//  GroupEntity.h
//
//  Generated by MD2 framework on Fri Jul 05 12:05:28 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

#import <CoreData/CoreData.h>
#import "Md2Library/DataTransferObject.h"

@interface GroupEntity : DataTransferObject

@property (retain, nonatomic) NSString* name;

@end

