//
//  GroupEntity.m
//
//  Generated by MD2 framework on Fri Jul 05 12:05:28 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

#import "GroupEntity.h"

@implementation GroupEntity

@dynamic name;

@end
