//
//  GroupTabController.h
//
//  Generated by MD2 framework on Fri Jul 05 12:05:29 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

#import "Md2Library/Controller.h"

@interface GroupTabController : Controller
@end