//
//  InitializeApplicationAction.m
//
//  Generated by MD2 framework on Fri Jul 05 12:05:30 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

#import "SpecificAppData.h"
#import "Md2Library/InitializeApplicationAction.h"
#import "Md2Library/HelpController.h"
#import "Md2Library/PickerController.h"
#import "Md2Library/DataMapper.h"
#import "Md2Library/Workflow.h"
#import "Md2Library/WorkflowManagement.h"
#import "StartUpActionAction.h"
#import "DetailTabController.h"
#import "GroupTabController.h"
#import "ContactsTabController.h"
#import "AutoGenerationActionAction.h"

@implementation InitializeApplicationAction

+(void) performAction: (Event *) event
{
	InitializeApplicationEvent *_event = (InitializeApplicationEvent *) event;
	
	
	// initialize controllers and appropriate views
	DetailTabController *detailTabController = [[DetailTabController alloc] init];
	UIImage *detailTabControllerImage = [UIImage imageNamed:@""];
	UITabBarItem* detailTabControllerItem = [[UITabBarItem alloc] initWithTitle: LocalizedKeyString(@"TI_detailTab") image: detailTabControllerImage tag: 0];
	detailTabController.tabBarItem = detailTabControllerItem;
	
	GroupTabController *groupTabController = [[GroupTabController alloc] init];
	UIImage *groupTabControllerImage = [UIImage imageNamed:@""];
	UITabBarItem* groupTabControllerItem = [[UITabBarItem alloc] initWithTitle: LocalizedKeyString(@"TI_groupTab") image: groupTabControllerImage tag: 0];
	groupTabController.tabBarItem = groupTabControllerItem;
	
	ContactsTabController *contactsTabController = [[ContactsTabController alloc] init];
	UIImage *contactsTabControllerImage = [UIImage imageNamed:@""];
	UITabBarItem* contactsTabControllerItem = [[UITabBarItem alloc] initWithTitle: LocalizedKeyString(@"TI_contactsTab") image: contactsTabControllerImage tag: 0];
	contactsTabController.tabBarItem = contactsTabControllerItem;
	
	NSArray* controllers = [NSArray arrayWithObjects: contactsTabController, detailTabController, groupTabController, nil];
	
	
	// initialize content providers
	GroupContentProviderContentProvider *groupContentProviderContentProvider = [[GroupContentProviderContentProvider alloc] init];
	ContactContentProviderContentProvider *contactContentProviderContentProvider = [[ContactContentProviderContentProvider alloc] init];
	GPSContentProvider *gpsContentProvider = [[GPSContentProvider alloc] init];
	
	
	// initialize workflows
	WorkflowManagement *workflowManagement = [WorkflowManagement workflowManagementWithWorkflows: [NSArray arrayWithObjects: nil]];
	
	
	// set up app data
	[AppData setPopoverController: [UIPopoverController alloc]];
	[AppData setTabBarController: [[UITabBarController alloc] init]];
	[AppData setControllers: controllers];
	[AppData setCurrentController: contactsTabController];
	[AppData setPickerController: [[PickerController alloc] init]];
	[AppData setHelpController: [[HelpController alloc] init]];
	[SpecificAppData setDetailTabController: detailTabController];
	[SpecificAppData setGroupTabController: groupTabController];
	[SpecificAppData setContactsTabController: contactsTabController];
	[SpecificAppData setGroupContentProviderContentProvider: groupContentProviderContentProvider];
	[SpecificAppData setContactContentProviderContentProvider: contactContentProviderContentProvider];
	[AppData setWorkflowManagement: workflowManagement];
	[AppData setEventActionMapping: [[NSMutableDictionary alloc] init]];
	[AppData setGPSContentProvider: gpsContentProvider];
	[AppData setModelVersion: @"1.0"];
	
	// configure popover and tab bar controller
    [AppData popoverController].delegate = _event.appDelegate;
    [AppData popoverController].popoverContentSize = PopoverContentSize;
	[AppData tabBarController].viewControllers = controllers;
	[AppData tabBarController].delegate = _event.appDelegate;
	[AppData tabBarController].selectedViewController = contactsTabController;
	
	
	// start actions
	[StartUpActionAction performCustomAction];
	[AutoGenerationActionAction performCustomAction];
	[contactsTabController loadData];
	
	
	// set up window
	[AppData setWindow: [[UIWindow alloc] initWithFrame: [[UIScreen mainScreen] bounds]]];
	[AppData window].backgroundColor = [UIColor whiteColor];
	[AppData window].rootViewController = [AppData tabBarController];
	[[AppData window] makeKeyAndVisible];
}

@end