//
//  RetrieveGPSPositionActionAction.m
//
//  Generated by MD2 framework on Fri Jul 05 12:05:30 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

#import "SpecificAppData.h"
#import "Md2Library/EventBindingAction.h"
#import "Md2Library/EventTrigger.h"
#import "Md2Library/RegisterMappingAction.h"
#import "Md2Library/UnregisterMappingAction.h"
#import "Md2Library/ValidatorBindingAction.h"
#import "Md2Library/ViewEvent.h"
#import "RetrieveGPSPositionActionAction.h"
#import "Md2Library/GPSUpdateAction.h"
#import "Md2Library/GPSUpdateEvent.h"

@implementation RetrieveGPSPositionActionAction

+(void) performAction: (Event *) event
{
	[self performCustomAction];
}

+(void) performCustomAction
{
	[GPSUpdateAction performAction: [GPSUpdateEvent eventWithBindings:
		[NSArray arrayWithObjects: 
			[GPSActionBinding bindingWithContentProvider: [SpecificAppData contactContentProviderContentProvider] dataKey: @"street"
				formattedString: @"%@"
				identifiers: [NSArray arrayWithObjects: @"street"]],
			[GPSActionBinding bindingWithContentProvider: [SpecificAppData contactContentProviderContentProvider] dataKey: @"city"
				formattedString: @"%@"
				identifiers: [NSArray arrayWithObjects: @"city"]],
			[GPSActionBinding bindingWithContentProvider: [SpecificAppData contactContentProviderContentProvider] dataKey: @"zipCode"
				formattedString: @"%@"
				identifiers: [NSArray arrayWithObjects: @"postalCode"]]
			]]];
}

@end