//
//  SpecificAppData.h
//
//  Generated by MD2 framework on Fri Jul 05 12:05:30 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

#import "DetailTabController.h"
#import "GroupTabController.h"
#import "ContactsTabController.h"
#import "GroupContentProviderContentProvider.h"
#import "ContactContentProviderContentProvider.h"
@class Workflow;

@interface SpecificAppData : NSObject
{
	DetailTabController *detailTabController;
	GroupTabController *groupTabController;
	ContactsTabController *contactsTabController;
	
	GroupContentProviderContentProvider *groupContentProviderContentProvider;
	ContactContentProviderContentProvider *contactContentProviderContentProvider;
	
}

@property (retain, nonatomic) DetailTabController *detailTabController;
@property (retain, nonatomic) GroupTabController *groupTabController;
@property (retain, nonatomic) ContactsTabController *contactsTabController;

@property (retain, nonatomic) GroupContentProviderContentProvider *groupContentProviderContentProvider;
@property (retain, nonatomic) ContactContentProviderContentProvider *contactContentProviderContentProvider;


+(DetailTabController *) detailTabController;+(GroupTabController *) groupTabController;+(ContactsTabController *) contactsTabController;
+(GroupContentProviderContentProvider *) groupContentProviderContentProvider;+(ContactContentProviderContentProvider *) contactContentProviderContentProvider;

+(void) setDetailTabController: (DetailTabController *) detailTabController;+(void) setGroupTabController: (GroupTabController *) groupTabController;+(void) setContactsTabController: (ContactsTabController *) contactsTabController;
+(void) setGroupContentProviderContentProvider: (GroupContentProviderContentProvider *) groupContentProviderContentProvider;+(void) setContactContentProviderContentProvider: (ContactContentProviderContentProvider *) contactContentProviderContentProvider;

@end