//
//  SpecificAppData.m
//
//  Generated by MD2 framework on Fri Jul 05 12:05:30 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

#import "SpecificAppData.h"
@implementation SpecificAppData

static SpecificAppData *instance;

@synthesize detailTabController, groupTabController, contactsTabController;
@synthesize groupContentProviderContentProvider, contactContentProviderContentProvider;

#pragma mark Initialization Methods

+(SpecificAppData *) instance
{
	@synchronized([SpecificAppData class])
	{
		if (!instance)
			instance = [[self alloc] init];
		return instance;
	}
	return nil;
}

+(id) alloc
{
	@synchronized([SpecificAppData class])
	{
		NSAssert(instance == nil, @"Attempted to allocate a second instance of a singleton.");
		instance = [super alloc];
		return instance;
	}
	return nil;
}

+(id) init
{
    return [self init];
}

#pragma mark Static Accessor Methods

+(DetailTabController *) detailTabController
{
    return [SpecificAppData instance].detailTabController;
}

+(GroupTabController *) groupTabController
{
    return [SpecificAppData instance].groupTabController;
}

+(ContactsTabController *) contactsTabController
{
    return [SpecificAppData instance].contactsTabController;
}


+(GroupContentProviderContentProvider *) groupContentProviderContentProvider
{
    return [SpecificAppData instance].groupContentProviderContentProvider;
}

+(ContactContentProviderContentProvider *) contactContentProviderContentProvider
{
    return [SpecificAppData instance].contactContentProviderContentProvider;
}



#pragma mark Static Manipulation Methods

+(void) setDetailTabController: (DetailTabController *) detailTabController
{
    [SpecificAppData instance].detailTabController = detailTabController;
}

+(void) setGroupTabController: (GroupTabController *) groupTabController
{
    [SpecificAppData instance].groupTabController = groupTabController;
}

+(void) setContactsTabController: (ContactsTabController *) contactsTabController
{
    [SpecificAppData instance].contactsTabController = contactsTabController;
}


+(void) setGroupContentProviderContentProvider: (GroupContentProviderContentProvider *) groupContentProviderContentProvider
{
    [SpecificAppData instance].groupContentProviderContentProvider = groupContentProviderContentProvider;
}

+(void) setContactContentProviderContentProvider: (ContactContentProviderContentProvider *) contactContentProviderContentProvider
{
    [SpecificAppData instance].contactContentProviderContentProvider = contactContentProviderContentProvider;
}



@end