//
//  StartUpActionAction.m
//
//  Generated by MD2 framework on Fri Jul 05 12:05:29 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

#import "SpecificAppData.h"
#import "Md2Library/EventBindingAction.h"
#import "Md2Library/EventTrigger.h"
#import "Md2Library/RegisterMappingAction.h"
#import "Md2Library/UnregisterMappingAction.h"
#import "Md2Library/ValidatorBindingAction.h"
#import "Md2Library/ViewEvent.h"
#import "StartUpActionAction.h"
#import "Md2Library/GotoControllerAction.h"
#import "RetrieveGPSPositionActionAction.h"
#import "Md2Library/PersistAction.h"
#import "Md2Library/PersistEvent.h"

@implementation StartUpActionAction

+(void) performAction: (Event *) event
{
	[self performCustomAction];
}

+(void) performCustomAction
{
	[EventBindingAction performAction: [EventBindingEvent eventWithMapping: [AppData eventActionMapping] viewEvent: [ViewEvent eventWithIdentifier: @"retrieveGPS1" eventType: OnTouch] action: [RetrieveGPSPositionActionAction action]]];
	[EventBindingAction performAction: [EventBindingEvent eventWithMapping: [AppData eventActionMapping] viewEvent: [ViewEvent eventWithIdentifier: @"editContactButton1" eventType: OnTouch] action: [GotoControllerAction actionWithEvent: [GotoControllerEvent eventWithWindow: [AppData window] tabBarController: [AppData tabBarController] currentController: [AppData currentController] nextController: [SpecificAppData detailTabController]]]]];
	[EventBindingAction performAction: [EventBindingEvent eventWithMapping: [AppData eventActionMapping] viewEvent: [ViewEvent eventWithIdentifier: @"addGroupButton1" eventType: OnTouch] action: [GotoControllerAction actionWithEvent: [GotoControllerEvent eventWithWindow: [AppData window] tabBarController: [AppData tabBarController] currentController: [AppData currentController] nextController: [SpecificAppData groupTabController]]]]];
	[EventBindingAction performAction: [EventBindingEvent eventWithMapping: [AppData eventActionMapping] viewEvent: [ViewEvent eventWithIdentifier: @"saveButton1" eventType: OnTouch] action: [PersistAction actionWithEvent: [PersistEvent eventWithContentProvider: [SpecificAppData contactContentProviderContentProvider]]]]];
	[EventBindingAction performAction: [EventBindingEvent eventWithMapping: [AppData eventActionMapping] viewEvent: [ViewEvent eventWithIdentifier: @"saveButton" eventType: OnTouch] action: [PersistAction actionWithEvent: [PersistEvent eventWithContentProvider: [SpecificAppData groupContentProviderContentProvider]]]]];
	[EventBindingAction performAction: [EventBindingEvent eventWithMapping: [AppData eventActionMapping] viewEvent: [ViewEvent eventWithIdentifier: @"saveButton2" eventType: OnTouch] action: [GotoControllerAction actionWithEvent: [GotoControllerEvent eventWithWindow: [AppData window] tabBarController: [AppData tabBarController] currentController: [AppData currentController] nextController: [SpecificAppData contactsTabController]]]]];
	[EventBindingAction performAction: [EventBindingEvent eventWithMapping: [AppData eventActionMapping] viewEvent: [ViewEvent eventWithIdentifier: @"saveButton3" eventType: OnTouch] action: [GotoControllerAction actionWithEvent: [GotoControllerEvent eventWithWindow: [AppData window] tabBarController: [AppData tabBarController] currentController: [AppData currentController] nextController: [SpecificAppData detailTabController]]]]];
	[EventBindingAction performAction: [EventBindingEvent eventWithMapping: [AppData eventActionMapping] viewEvent: [ViewEvent eventWithIdentifier: @"retrieveGPS" eventType: OnTouch] action: [RetrieveGPSPositionActionAction action]]];
	[EventBindingAction performAction: [EventBindingEvent eventWithMapping: [AppData eventActionMapping] viewEvent: [ViewEvent eventWithIdentifier: @"editContactButton" eventType: OnTouch] action: [GotoControllerAction actionWithEvent: [GotoControllerEvent eventWithWindow: [AppData window] tabBarController: [AppData tabBarController] currentController: [AppData currentController] nextController: [SpecificAppData detailTabController]]]]];
	[EventBindingAction performAction: [EventBindingEvent eventWithMapping: [AppData eventActionMapping] viewEvent: [ViewEvent eventWithIdentifier: @"addGroupButton" eventType: OnTouch] action: [GotoControllerAction actionWithEvent: [GotoControllerEvent eventWithWindow: [AppData window] tabBarController: [AppData tabBarController] currentController: [AppData currentController] nextController: [SpecificAppData groupTabController]]]]];
	[EventBindingAction performAction: [EventBindingEvent eventWithMapping: [AppData eventActionMapping] viewEvent: [ViewEvent eventWithIdentifier: @"saveButton1" eventType: OnTouch] action: [GotoControllerAction actionWithEvent: [GotoControllerEvent eventWithWindow: [AppData window] tabBarController: [AppData tabBarController] currentController: [AppData currentController] nextController: [SpecificAppData contactsTabController]]]]];
	[EventBindingAction performAction: [EventBindingEvent eventWithMapping: [AppData eventActionMapping] viewEvent: [ViewEvent eventWithIdentifier: @"saveButton" eventType: OnTouch] action: [GotoControllerAction actionWithEvent: [GotoControllerEvent eventWithWindow: [AppData window] tabBarController: [AppData tabBarController] currentController: [AppData currentController] nextController: [SpecificAppData detailTabController]]]]];
}

@end